---
name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

  release-image:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [ gie-test, python-test, k8s-test ]
    steps:
    - uses: actions/checkout@v2.3.2

    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Prepare Image
      run: |
        cp .github/workflows/*.Dockerfile artifacts/
        cd artifacts
        tar -xf ./gae-${{ github.sha }}/gae.tar
        tar -xf ./gle-${{ github.sha }}/gle.tar
        tar -xf ./gie-${{ github.sha }}/gie.tar
        tar -xf ./manager-${{ github.sha }}/manager.tar
        sudo docker build -t registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:${{ github.sha }} \
                          --network=host \
                          -f ./graphscope.Dockerfile .
        sudo docker build -t registry.cn-hongkong.aliyuncs.com/graphscope/maxgraph_standalone_manager:1.0 \
                          --network=host \
                          -f ./manager.Dockerfile .

    - name: Release images
      run: |
        echo ${{ secrets.ALIYUN_TOKEN }} | sudo docker login --username=grape_dev registry.cn-hongkong.aliyuncs.com --password-stdin
        sudo docker tag registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:${{ github.sha }} \
                        registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:latest
        sudo docker push registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:${{ github.sha }}
        sudo docker push registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:latest
        
        sudo docker push registry.cn-hongkong.aliyuncs.com/graphscope/maxgraph_standalone_manager:1.0
